version: '3.0'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - 5432:5432
