version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    volumes:
      - ./src/db/migrations/versions:/src/db/migrations/versions
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env.docker
